config/routes.rb
Fp::Application.routes.draw do
      
  root :to => 'home#web_page'
  

  resources :prayers
    
  
  #get routes  
  get "worldwide"=> "prayers#worldwide"
  get "home/index"
  get "home/web_page"
  get "donate"=>"donate#prayer"
  get "settings"=> "users#settings"
  
   #match routes
  #authentification to the session in omniauth
  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout
  
 
end

app/models/prayer.rb
class Prayer < ActiveRecord::Base
 belongs_to :user
 paginates_per 5
 def up
   
  add_column :user
 end
end

app/models/user.rb
class User < ActiveRecord::Base
   has_many :prayers
   has_many :sessions
   def self.create_with_omniauth(omniauth)

   create! do |user|
       user.provider = omniauth["provider"]
       user.uid = omniauth["uid"]
       user.name = omniauth["info"]["name"]
       user.image = omniauth["info"]["image"]
       user.token = omniauth["credentials"]["token"]
       if user.save        
         #format.html { redirect_to "/auth/:provider/callback", :notice => 'User wass full created' }
       else
        #format.html { redirect_to root_url, :notice => 'User not created' }
       end
       return user
     end
     
    def self.create_from_hash!(hash)
      create(:name => hash['info']['name'])
    end


   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery
    before_filter :redirect_https
    helper_method  :users
    helper_method :current_user
       helper_method :current_user_name
       helper_method :current_user_image
       helper_method :current_user_id
       helper_method :current_user_uid
       helper_method :current_pray
    before_filter :authorize
   
  
  private
  
  def redirect_https  
    if Rails.env == "production"
         if !request.ssl?      
            redirect_to "https://friendprayer.org"
         end
    else
      
       #if !request.ssl?
        #redirect_to "https://friendprayer.org"
       #end
      
    end
  end
      
 
  def current_user
    
    current_user ||= User.find(session[:user_id]) if session[:user_id]
    
  end
       
  def users
     @users = User.all
   end
   
   def current_pray
     @prayer = Prayer.find(params[:id])
   end
       
  def not_authenticated
    redirect_to root_url, :alert => "First login to access this page."
  end
  protected
   def authorize
      unless User.find_by_id(session[:user_id])
      redirect_to root_url, :notice => "Please log in"
      end 
  end
end

app/controllers/donate_controller.rb
class DonateController < ApplicationController
  skip_before_filter :redirect_https
  skip_before_filter :authorize
  def prayer
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authorize
  def index
    redirect_to root_path
  end
  
  def web_page
    if current_user
      redirect_to :prayers
    else
    end
  end
  
end

app/controllers/prayers_controller.rb
class PrayersController < ApplicationController
  skip_before_filter :redirect_https
   # GET /prayers
  # GET /prayers.json
  def index
  #se creo en consola p=Prayer.find(#prayer)
  #poner p.user
    @prayers = current_user.prayers('id').reverse_order.page params[:page]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @prayers }
    end
   
  end

  # GET /prayers/1
  # GET /prayers/1.json
  def show
    @prayer = Prayer.find(params[:id])
  end

  # GET /prayers/new
  # GET /prayers/new.json
  def new
    @prayer = Prayer.new(params[:prayer])
    
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @prayer }
    end
  end

  # GET /prayers/1/edit
  def edit
    @prayer = Prayer.find(params[:id])
  end

  # POST /prayers
  # POST /prayers.json
  def create
    @prayer = Prayer.new(params[:prayer])
    @prayer.user=current_user
    @prayer.name=current_user.name
    @prayer.image=current_user.image
    respond_to do |format|
      if @prayer.save
        format.html { redirect_to :back, :notice => 'Prayer was successfully created.' }
        format.json { render :json => @prayer, :status => :created, :location => @prayer }
      else
        format.html { render :action => "new" }
        format.json { render :json => @prayer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /prayers/1
  # PUT /prayers/1.json
  def update
    @prayer = Prayer.find(params[:id])

    respond_to do |format|
      if @prayer.update_attributes(params[:prayer])
        format.html { redirect_to :back, :notice => 'Prayer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @prayer.errors, :status => :unprocessable_entity }
       
      end
    end
  end

  # DELETE /prayers/1
  # DELETE /prayers/1.json
  def destroy
    @prayer = Prayer.find(params[:id])
    @prayer.destroy

    respond_to do |format|
      format.html { redirect_to prayers_url }
      format.json { head :no_content }
    end
  end 
 
 def worldwide
    #se declaro en consola g=Prayer.all
    @prayers = Prayer.order(:id).reverse_order.page(params[:page])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :redirect_https
   skip_before_filter :authorize
        def create
          omniauth = request.env["omniauth.auth"]
          user = User.find_by_provider_and_uid(omniauth["provider"], omniauth["uid"]) || User.create_with_omniauth(omniauth)
          puts user
          session[:user_id] = user.id
          redirect_to prayers_url, :notice => "Signed in!"
        end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   skip_before_filter :redirect_https
   def new
    @user = User.new(params[:user])
   
    @user=current_user.name
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end
  
 
  
  #def 
 
end

app/helpers/donate_helper.rb
module DonateHelper
end

app/helpers/prayers_helper.rb
module PrayersHelper
  def character_count(field_id, update_id, options = {})
      function = "$('#{update_id}').innerHTML = $F('#{field_id}').length;"
      out = javascript_tag(function) # set current length
      out += observe_field(field_id, options.merge(:function => function)) # and observe it
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/donate/prayer.html.erb
<!DOCTYPE html>
<html>
<body>
<div id="payments">
<center>
</br>
</br>
</br>
<h1 style="color: #000">Invitanos una taza de café</h1>
<h1 style="color: #2BB3E5">Invite me a coffee</h1>
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="RNV7UWU8K8D8U">
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypalobjects.com/es_XC/i/scr/pixel.gif" width="1" height="1">
</form>
</br>
</br>
<h1 style="color: #000">Apollanos a mantener el servicio</h1>
<h1 style="color: #2BB3E5">Help us to keep the service</h1>
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="XBWYHE36KF6DL">
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypalobjects.com/es_XC/i/scr/pixel.gif" width="1" height="1">
</form>
</br>
</br>
</br>
</br>
</center>
</div>
</body>
<footer id="footer">
<center><h3><%= link_to "www.friendprayer.org", "https://friendprayer.org" %>||<a data-toggle="modal" href="#modalite"><i>Políticas de uso del sitio</i></a></center></h3>
</footer>
</html>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<body>
<center>
<div id="bodyp">
 <div class="modal hide" id="modale">
	  <div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal">×</button>
	    Friend prayer
	  </div>
	  <div class="modal-body">
	  <iframe width="520" height="415" src="http://www.youtube.com/embed/ylvGR6VrJaI" frameborder="0" allowfullscreen></iframe>
	  </div>
	  <div class="modal-footer">
	   	<p>Friendprayer.org todos lo derechos reservados</p>
	   </div>
	  </div>
	</div>
</div>
	</center>

<div id="name">
<div class="navbar">
<div class="navbar-inner">
<div class="container">
  <ul class="nav nav-tabs">
    <li class="active" style="color:#fff"><a href="#tab1" data-toggle="tab">Home</a></li>
    <li ><a href="#tab2" data-toggle="tab">Objetivo</a></li>
    <li ><a href="#tab3" data-toggle="tab">Creadores</a></li>
    <li ><a href="#tab4" data-toggle="tab">Blog</a></li>
 </div> 
</div>  
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="tab1">
	<div id="bodyp">
		</br>
      <p>
    <center>Friend Prayer es una web que aspira a ser una cadena de oración mundial.</center>
      </p>
      </br>
      </br>
        <center> 
              <div class=" btn btn-medium btn-warning" href="/auth/facebook"> 
			   <h1> <%= link_to "Ingresa con Facebook", "/auth/facebook" %> </h1>

			   </div>
		</center>
		 </br>
	     </br>
      <center>	
	  	<div class="btn btn-primary" data-toggle="modal" href="#modale"><h1>reproduce el video de friend prayer</h1></div>
      </center> 
     </br>
      </br>
    </div>
    </div>
   	<div class="tab-pane" id="tab2">
	<div id="bodyp">
      <p>Nuestro objetivo es crear la cadena de oración mas grande del mundo pidiendo por situaciones que a todos nos aquejan como sociedades, poner una oración en este sitio no solo crea esperanza sino que demuestra interés por solucionar problemas que a todos nos aquejan.</p>
	</br> 
	<p>    
	<b>¡¡También puedes pedir individualmente y alguien  en un lugar muy lejano seguramente orara por tí!!</b>
	 </p>
	</div>
	</div>
    <div class="tab-pane" id="tab3">
	<div id="bodyp">
	<p>Esta es una web desarrollada en css, javascript y Ruby on Rails, que de preferencia debe ser vista en navegadores como google chrome o mozila firefox</p></br>
      <p>Fue creada por:</p>
     </br> 
	  <center>
		<ul class="nav nav-list">
	    <b> <li>
		<center>
		<div class="badge">
					<center>
		    <a href="http://www.alfredoreyes.me">José Alfredo Reyes de Antuñano</a>
	
		     <a href="http://www.leonrangel.me">José León Rangel Reyes</a>
		            </center>
		</div>
		
		</b>
		    </li> 
		</ul>
	  </center>	   
	 </br> 
     </br>
    </div>
    </div>
    <div class="tab-pane" id="tab4">
      <div id="bodyp">
	    <iframe src="http://friendprayer.tumblr.com/" frameborder="0" width="100%" height="2000"></iframe>   
	  </div>
    </div>
  </div>
</div>
</div>
</div>
<body>
	<footer id="footer">
	<center><h3><%= link_to "www.friendprayer.org", "https://friendprayer.org" %>||<a data-toggle="modal" href="#modalite"><i>Políticas de uso del sitio</i></a></center></h3>
	</footer>
</html>	

app/views/home/web_page.html.erb
<div class="container">
<div class="span13">
    <div class="navbar">
    <div class="navbar-inner">
    <div class="container">
         <h1>Friend Prayer</h1>
    </div>
    </div>
    </div>

        <div class="span5">
          <h2> ¿Quienes Somos?</h2>
           <p>Somos jovenes que intentamos cambiar al mundo mediante el acto mas antiguo de fe "la oración".</p>
        <div>
        <div class="span9">
            <div class="span5" style="margin-top:20px;margin-bottom:20px; margin-right:20px;margin-left:-35px;">
              <%= render :partial => 'shared/like_photo'%>
            </div>
        <div class="span3" style="background-color:#1D8FD0">
            <center>
            <h1><%= link_to "Ingresa con Facebook", "/auth/facebook"%></h1>
            </center>
        </div>
        </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
  <title>FriendPrayer</title>
  <link rel="stylesheet" href="app/stileshets/reset.css" type="text/css" />
  <link rel="stylesheet" href="app/stileshets/style.css" type="text/css" />
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "boostrap-modal" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag "favicon.ico" %>
  

</head>
<div class="alert alert-block"><%= notice %>
</div>
</div>
<div id="container2">
<div id="header">
<div id="logo"><h1>Friend Prayer</h1> <a href=""><%=link_to image_tag("logo.png")  %></a></div>
<div id="slogan"><h2>Now you can easily share prayers with your friends all over the world!</h2><a href=""><%=link_to image_tag("slogan.png")%></a></div>
</div>
<div id="navs">
    <%= render :partial => "shared/principal_menu"%>
  <div id="user_nav">
  <% if current_user %>

    <h2> Welcome: <%= current_user.name %>! 
   	<div class=" btn btn-info">
   	<div id="friends">
     <p><%= link_to "Invite ++", "#", :id => "invite_fb_friends"  %></p>
                     
     <div id="fb-root"></div>
     <%= render :partial => "shared/invite_friends"%>
    </div>
   </h2>
  <% else %>
   	<div class="pull-right">
   <div class="btn btn-success" data-toggle="modal" href="#myModal">Ayuda?</div>
   </div>
 
  <% end %>
 
</br>


<body>
    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-35681116-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    </script>	
<%= yield %>

</div>

</body>
</html>
   <%= render :partial => "shared/modals_layout"%>
 </div>

app/views/prayers/_form.html.erb
<%= form_for(@prayer) do |f| %>
  <% if @prayer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prayer.errors.count, "error") %> prohibited this prayer from being saved:</h2>

      <ul>
      <% @prayer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <br />
    
  </div>
  <div class="field">
  <%= current_user.name %>
  </div>
  <div class="field">
    <%= f.label :pray %><br />
    <%= f.text_area :pray %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/prayers/edit.html.erb
<h1>Editing prayer</h1>

<%= render 'form' %>

<%= link_to 'Show', @prayer %> |
<%= link_to 'Back', prayers_path %>

app/views/prayers/index.html.erb
<!DOCTYPE html>
<html>
<body>
<%= form_for(@prayer=Prayer.new) do |f| %>

 <div class="field">
<center>
<%= f.text_area :pray, :class => "textarea" %>
</center>
<%=f.submit "Oración", :class => "btn btn-info btn-large"%>

</div>

<div id="name">
<link rel="stylesheet" href="app/stileshets/reset.css" type="text/css"/>
<link rel="stylesheet" href="app/stileshets/style.css" type="text/css"/>

<%end%>
<div class="imput-append" style = "padding:10px;">
<p>
   <% @prayers.each do |prayer|%>
    <div class="img"><%= image_tag(current_user.image) %> Pray:<%= prayer.pray%> </div>
 
          <% if Rails.env == "production"%>
          <div class="fb-like" data-href="https://friendprayer.org/prayers/<%= prayer.id %>" data-send="true" data-width="450" data-show-faces="true" data-font="arial"></div>
          <div id="fb-root"></div>
          <script>(function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/es_ES/all.js#xfbml=1&appId=236652113026256";
            fjs.parentNode.insertBefore(js, fjs);
          }(document, 'script', 'facebook-jssdk'));</script>
          <%else%>
          <div class="fb-like" data-href="https://localhost:3000/prayers/<%= prayer.id %>" data-send="true" data-width="450" data-show-faces="true" data-font="arial"></div>
          <div id="fb-root"></div>
          <script>(function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/es_ES/all.js#xfbml=1&appId=220846244674086";
            fjs.parentNode.insertBefore(js, fjs);
          }(document, 'script', 'facebook-jssdk'));</script>
          <%end%>
   <pre>
     
     
     <div class="pull-right"><span  class="label label-important"><%= link_to 'Delete', prayer, :confirm => 'Estas seguro de borrar esta oración?/ Are you shure?', :method => :delete %></span></div>
      <div class="pull-right"><span class="label label-success"><%= link_to 'Edit', edit_prayer_path(prayer) %></span></div>
      <div class="pull-right"><span class="label label-info"><%=link_to 'Comment >>', prayer %></span></div>
     
</pre>
  
<% end %>
</br>
</p>
</div>
</br>
</div>
<center>
<br />	
<%= paginate @prayers%>
</center>
</body>
<footer id="footer">
<center><h3><%= link_to "www.friendprayer.org", "https://friendprayer.org" %>||<a data-toggle="modal" href="#modalite"><i>Políticas de uso del sitio</i></a></center></h3>
</footer>
</html>

app/views/prayers/new.html.erb
<h1>New prayer</h1>

<%= render 'form' %>

<%= link_to 'Back', prayers_path %>

app/views/prayers/show.html.erb
    <p id="notice"><%= notice %></p>

    <p>
        <div class="comments" style="margin-left:35px;">
            <%= @prayer.pray %></br></br>
            <%= render :partial => "shared/like_share"%>  
        </div>
      <%= render :partial => "shared/comments"%>
    </p>


    
    

app/views/prayers/worldwide.html.erb
<!DOCTYPE html>
<html>
<body>
<%= form_for(@prayer=Prayer.new) do |f| %>
 <div class="field">
 <center>
 <%= f.text_area :pray, :class => "textarea" %>
 </center>
 <%=f.submit "Oración", :class => "btn btn-info btn-large"%>

 </div>
 
<div id="name">

<link rel="stylesheet" href="app/stileshets/reset.css" type="text/css"/>
<link rel="stylesheet" href="app/stileshets/style.css" type="text/css"/>
<%end%>
<p>
<div class="imput-append" style = "padding:10px;">

<% @prayers.each do |prayer| %>    
	    <div class="img"> <%= image_tag(prayer.image) %> Pray:<%= prayer.pray %></div>
	    <% if Rails.env == "production"%>
        <div class="fb-like" data-href="https://friendprayer.org/prayers/<%= prayer.id %>" data-send="true" data-width="450" data-show-faces="true" data-font="arial"></div>
        <div id="fb-root"></div>
        <script>(function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/es_ES/all.js#xfbml=1&appId=236652113026256";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>
        <%else%>
        <div class="fb-like" data-href="http://localhost:3000/prayers/<%= prayer.id %>" data-send="true" data-width="450" data-show-faces="true" data-font="arial"></div>
        <div id="fb-root"></div>
        <script>(function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/es_ES/all.js#xfbml=1&appId=220846244674086";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>
        <%end%>	    	     
       <pre> By:<%= prayer.name %>
       <div class="pull-right"><span class="label label-info"><%=link_to 'Comment >>', prayer %></span></div></pre>
<% end %>
</p>
<br />

</div>
</div>
<center><%= paginate @prayers%></center>

</body>
<footer id="footer">
<center><h3><%= link_to "www.friendprayer.org", "https://friendprayer.org" %>||<a data-toggle="modal" href="#modalite"><i>Políticas de uso del sitio</i></a></center></h3>
</footer>
</html>

app/views/shared/_comments.html.erb
<% if Rails.env == "production"%>
<center>
<div class = "comments">
<div class="fb-comments" data-href="https://friendprayer.org/prayers/<%= current_pray.id %>" data-num-posts="10" data-width="570"></div>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_ES/all.js#xfbml=1&appId=236652113026256";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
</div>
</center>
<%end%>

<% if Rails.env == "development"%>
<center>
<div class = "comments">
<div class="fb-comments" data-href="http://localhost:3000/prayers/<%= current_pray.id %>" data-num-posts="10" data-width="570"></div>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_ES/all.js#xfbml=1&appId=220846244674086";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
</div>
</center>

<%end%>

app/views/shared/_invite_friends.html.erb
<script src="http://connect.facebook.net/en_US/all.js"></script>
<% if Rails.env == "production"%>
 <script>
   $(function(){

     $("a#invite_fb_friends").click(function() {
       FB.init({ 
          appId:'236652113026256', 
          cookie:false, 
          status:true
       });

       FB.ui({ method: 'apprequests', message: ' <%= current_user.name %> Escribe tus oraciones y recibe las de tus amigos !!'});
     });
   });
 </script>
 <%else%>
 <script>
    $(function(){

      $("a#invite_fb_friends").click(function() {
        FB.init({ 
           appId:'220846244674086', 
           cookie:false, 
           status:true
        });

        FB.ui({ method: 'apprequests', message: ' <%= current_user.name %> Escribe tus oraciones y recibe las de tus amigos !!'});
      });
    });
  </script>
 <%end%>

app/views/shared/_like_photo.html.erb
<% if Rails.env == "production"%>
<div class="fb-like-box" data-href="https://www.facebook.com/pages/friend-prayer/200872926630775" data-width="400" data-show-faces="true" data-stream="true" data-header="true"></div>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_ES/all.js#xfbml=1&appId=236652113026256";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<%else%>
<div class="fb-like-box" data-href="http://www.facebook.com/pages/friend-prayer/200872926630775" data-width="400" data-show-faces="true" data-stream="true" data-header="true"></div>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_ES/all.js#xfbml=1&appId=336243296469875";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<%end%>

app/views/shared/_like_public_wi.html.erb
<% if Rails.env == "production"%>
<div class="fb-like" data-href="https://friendprayer.org/prayers/<%= prayer.id %>" data-send="true" data-width="450" data-show-faces="true" data-font="arial"></div>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_ES/all.js#xfbml=1&appId=236652113026256";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<%else%>
<div class="fb-like" data-href="http://localhost:3000/prayers/<%= prayer.id %>" data-send="true" data-width="450" data-show-faces="true" data-font="arial"></div>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_ES/all.js#xfbml=1&appId=220846244674086";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<%end%>

app/views/shared/_principal_menu.html.erb
    <ul class="nav nav-tabs">
        <li id="prayers" ><%= link_to "Prayers", prayers_path %></li>
        <li id="worldwide"><%= link_to "World Wide", worldwide_path %></li>
        <!--<li id="settings"><a href="worldwide" class="activeprayers">Worldwide</a></li>-->
        <li id="donate"><%= link_to "Donate", donate_path %></li>
        <% if current_user%>
        <li ><a><%= link_to "Salir", "/signout" %></a></li>   
        <%end%>
    </ul>
    </br>
    </br>